src/app/(app)/chat/page.js
commented chat module, interim solution for chat module build error
=> commented chat module, interim solution for chat module build error

src/stores/ChatContext.js
=> Fix build errors in chat page

src/app/(app)/layout.js, src/app/page.js
=> fixed some errors in orders

src/app/(app)/product/page.js
applied filter that only suppliers can add,edit and delete products
=> applied filter that only suppliers can add,edit and delete products

src/app/(app)/brand/page.js
implemented that only supplier can add,edit and remove brand
=> implemented that only supplier can add,edit and remove brand

src/components/orders/QuotationComponentForm.js
Implemente that only supplier can send quotation
=> Implemente that only supplier can send quotation

src/app/(app)/layout.js, src/app/(app)/user-management/[slug]/page.js, src/app/(app)/user-management/page.js, src/app/(auth)/layout.js, src/app/(auth)/register/page.js, src/components/Sidebar.js, src/components/user-management/AddUserModal.js, src/components/user-management/EditUserModal.js, src/components/user-management/ManageRoleModal.js, src/hooks/auth.js
refractor user-management and authentication
=> refractor user-management and authentication

src/components/orders/QuotationComponentForm.js
=> Fix QuotationForm errors

src/app/(app)/brand/page.js
remove dependency array in useEffect of brand
=> remove dependency array in useEffect of brand

src/app/(app)/brand/page.js, src/app/(app)/category/page.js, src/app/(app)/product/page.js
fixed infinite loop issues in category,brand and product modile
=> fixed infinite loop issues in category,brand and product modile

src/app/(app)/chat/page.js, src/hooks/useEcho.js
Migrated to Laravel Reverb to Pusher
=> Migrated to Laravel Reverb to Pusher

next.config.mjs, src/app/(app)/product/page.js, src/components/material-ui/Item.js, src/components/orders/QuotationComponentForm.js, src/components/product/ProductForm.js, src/components/product/ViewProductDialog.js, src/data/products.js, src/hooks/api/product.js
=> Building010825

src/app/(app)/product/page.js, src/components/Sidebar.js
=> Finalize Product Module

src/app/(auth)/login-otp/page.js
change default landing page to products
=> change default landing page to products

next.config.mjs, src/app/(app)/product/page.js, src/components/product/ProductForm.js, src/components/product/ViewProductDialog.js
=> added price ex in products

src/app/(app)/product/page.js, src/components/product/ProductListSkeleton.js
implemented skeleton inproduct module
=> implemented skeleton inproduct module

package-lock.json, package.json, src/app/(app)/product/page.js
Applied filter in product list
=> Applied filter in product list

src/app/(app)/product/page.js
added product image in the product table
=> added product image in the product table

src/app/(auth)/profile/page.js, src/components/Sidebar.js
=> Add link to update profile

src/app/(app)/product/page.js, src/app/(auth)/profile/page.js, src/components/product/ProductForm.js
Made price and image optional in store product
=> Made price and image optional in store product

src/app/(app)/product/page.js
=> add supplier to proudct list

src/app/(app)/product/page.js
=> fix product

src/app/(app)/department/page.js, src/components/Sidebar.js, src/components/department/DepartmentForm.js, src/components/department/DepartmentList.js, src/components/department/DepartmentListItem.js, src/components/department/DepartmentListSkeleton.js, src/components/material-ui/ToolTipIconButton.js, src/hooks/api/department.js
created department management module
=> created department management module

src/components/home-page/Footer.js, src/components/home-page/OtherLink.js
added supplier work instructions in home page
=> added supplier work instructions in home page

src/app/(app)/product/page.js
=> QA tested send quotation form

src/app/(app)/brand/page.js
QA tested and fixed brand module
=> QA tested and fixed brand module

src/components/department/DepartmentForm.js
=> QA Tested depasrtment module

src/app/(app)/supplier-document/compliance/page.js, src/components/supplier-document/compliance/ComplianceDocumentListComponent.js
=> fixed some minor bugts

src/app/(auth)/login/page.js
=> fixed character error

src/components/supplier/supplier-store.js
=> fix build issues
